name: jenkins_manager
description: Jenkins Manager
version: 0.3.0+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^2.1.1
  stacked_services: ^0.8.5

  http: ^0.13.2
  json_annotation: ^4.0.0

  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.0.1
  stacked_generator: 0.4.1
  json_serializable: ^4.1.1

  effective_dart: ^1.3.1
  dart_enum_to_string_check: ^0.7.2
  dart_code_metrics: ^3.2.2

flutter:
  uses-material-design: true
